name: Compliance

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3.10
